### ISSUE TITLE
add more recipe code

### ISSUE THREAD

**Issue by amaravindmenon** [amaravindmenon/recipe#1]
Help us to add more recipe codes so that it create a large data set

**Comment by DelayCoderz** [comment]
@amaravindmenon assign me

**Comment by wimanshaherath** [comment]
can i work on this?

**Comment by DelayCoderz** [comment]
what do you mean ??

**Comment by amaravindmenon** [comment]
> @amaravindmenon assign me

Sorry someone is already working on it

**Comment by amaravindmenon** [comment]
> can i work on this?

Sorry someone is already working on it

**Comment by DelayCoderz** [comment]
i finished add some new recep can you see it ??
